### ISSUE TITLE
Custom localizations break after reloading save

### ISSUE THREAD

**Issue by chaorace** [chaorace/Civ6-UIFiles#1]
Any LOC that comes from new mod files will only work for the first time a game is loaded. In other words: loading a save while the mod is already loaded breaks them.

To reproduce: load a mod with custom LOC text (Better Trade Screen, for example) and start a game. At this point, the custom LOC text should display correctly. Now create a save from this game and load it from the in-game escape menu, now all custom LOC text is broken (in the case of Better Trade Screen, many of the checkboxes in the trade route panels)

This bug forces mod makers to not localize! I have a Chinese LOC ready to integrate in CQUI and I cannot accept it because of this issue 👎

**Comment by astog** [comment]
@chaorace I thought this was fixed with the Winter update?

**Comment by chaorace** [comment]
@astog I heard custom art definitions were fixed, but I dug around all day looking to see if custom LOCs were fixed and came up blank. If they are fixed then that's amazing! (and perhaps a little embarrassing since I just got around to dedicating issue #1 to a possibly invalid problem!)

**Comment by chaorace** [comment]
Yep, this is definitely fixed in the winter patch (1.0.0.56)
